# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ lib, ... }:

{
  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "vmd" "nvme" "usbhid" "usb_storage" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    {
      device = "/dev/disk/by-uuid/0cdc2f83-310d-4c4f-aaaf-5b94afad426a";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    {
      device = "/dev/disk/by-uuid/FCF5-8B05";
      fsType = "vfat";
    };

  fileSystems."/mnt/data-b" =
    {
      device = "/dev/disk/by-uuid/ad3ed77b-9f50-4557-9712-9f85005ff07a";
      fsType = "ext4";
    };

  swapDevices =
    [{ device = "/dev/disk/by-uuid/1918e35f-be18-4ca8-a179-9a4e2e5107f8"; }];

  powerManagement.cpuFreqGovernor = lib.mkDefault "performance";
}

